name: govtech_mobile
description: Application mobile citoyenne pour le systÃ¨me GovTech national.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  provider: ^6.1.2
  pdf: ^3.9.0
  printing: ^5.10.0
  

  # ðŸ§  Ã‰tat global
  flutter_riverpod: ^2.4.0

  # ðŸ” Stockage sÃ©curisÃ© pour le JWT
  flutter_secure_storage: ^9.0.0

  # ðŸŒ RequÃªtes HTTP
  dio: ^5.3.2

  # ðŸŽ¨ Fonts modernes
  google_fonts: ^6.1.0

  # ðŸ§­ Navigation
  go_router: ^13.0.0

  # ðŸ“± Responsive UI
  flutter_screenutil: ^5.9.0

  # ðŸ“¦ JSON parsing (modÃ¨les)
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ðŸ§° GÃ©nÃ©ration de code
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/